"""
GMXEMATrendWETH Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import GMXEMATrendWETHStrategy
except ImportError:
    from strategy import GMXEMATrendWETHStrategy

__all__ = [
    "GMXEMATrendWETHStrategy",
]
